CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE category (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL,
    slug VARCHAR NOT NULL,
    CONSTRAINT "PK_category" PRIMARY KEY (id)
);

CREATE TABLE "Grupo" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Slug" text NOT NULL,
    CONSTRAINT "PK_Grupo" PRIMARY KEY ("Id")
);

CREATE TABLE "Tag" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Slug" text NOT NULL,
    CONSTRAINT "PK_Tag" PRIMARY KEY ("Id")
);

CREATE TABLE usuario (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL,
    email text NOT NULL,
    passwordhash text NOT NULL,
    bio text NOT NULL,
    image text NOT NULL,
    slug VARCHAR NOT NULL,
    github text NOT NULL,
    CONSTRAINT "PK_usuario" PRIMARY KEY (id)
);

CREATE TABLE post (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR NOT NULL,
    summary text NOT NULL,
    body text NOT NULL,
    slug text NOT NULL,
    createdate timestamp(6) without time zone NOT NULL DEFAULT TIMESTAMP '2024-11-19T15:43:45.851554',
    lastupdatedate timestamp(6) without time zone NOT NULL DEFAULT TIMESTAMP '2024-11-19T15:43:45.851633',
    categoryid integer NOT NULL,
    authorid integer NOT NULL,
    CONSTRAINT "PK_post" PRIMARY KEY (id),
    CONSTRAINT "FK_Post_Author" FOREIGN KEY (authorid) REFERENCES usuario (id) ON DELETE CASCADE,
    CONSTRAINT "FK_Post_Category" FOREIGN KEY (categoryid) REFERENCES category (id) ON DELETE CASCADE
);

CREATE TABLE userrole (
    "RoleId" integer NOT NULL,
    "UsuarioId" integer NOT NULL,
    CONSTRAINT "PK_userrole" PRIMARY KEY ("RoleId", "UsuarioId"),
    CONSTRAINT "FK_UserRole_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Grupo" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRole_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES usuario (id) ON DELETE CASCADE
);

CREATE TABLE postag (
    "PostId" integer NOT NULL,
    "TagId" integer NOT NULL,
    CONSTRAINT "PK_postag" PRIMARY KEY ("PostId", "TagId"),
    CONSTRAINT "FK_PostTag_PostId" FOREIGN KEY ("PostId") REFERENCES "Tag" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PostTag_TagId" FOREIGN KEY ("TagId") REFERENCES post (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Category_Slug" ON category (slug);

CREATE INDEX "IX_post_authorid" ON post (authorid);

CREATE INDEX "IX_post_categoryid" ON post (categoryid);

CREATE UNIQUE INDEX "IX_Post_Slug" ON post (slug);

CREATE INDEX "IX_postag_TagId" ON postag ("TagId");

CREATE INDEX "IX_userrole_UsuarioId" ON userrole ("UsuarioId");

CREATE UNIQUE INDEX "IX_Usuario_Slug" ON usuario (slug);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241119194346_InitialCreation', '8.0.11');

COMMIT;

